#!/bin/bash
basefile=$1
outputfile=$2
if [ -z "$outputfile" ]; then
    outputfile="a.out"
fi

cd ./shader-compiler/build
cmake .. ..
make -j8
cd ../..

./shader-compiler/build/shader_tool $basefile -- -std=c++20 -I./tensor  --gcc-toolchain=/usr   -isystem /usr/lib/gcc/x86_64-redhat-linux/16/include -fsyntax-only -DSTBI_NO_SIMD

# clang
compiler="clang++-19"

cat "shad.cpp" > "tmp.cu"
hipcc shad.cpp -o hip.o -c -I./tensor -std=c++20 -ggdb -O3 -march=native &
nvcc -ccbin=$compiler tmp.cu  -c -o nvidia.o -I./tensor -std=c++20 -Xcompiler -fPIC -Xcompiler -ggdb -O3 -Xcompiler -march=native
# include libraries for SDL3, OpenGL, GLEW, HIP, CUDA and vulkan
$compiler hip.o nvidia.o -o $outputfile -lSDL3 -lGL -lGLEW -std=c++20 -lamdhip64 -lcudart -L/usr/local/cuda/lib64 -I./tensor -lvulkan -ggdb -O3 -march=native
# include libraries for SDL3, OpenGL, GLEW, HIP, CUDA and vulkan

rm "tmp.cu";
rm hip.o
# rm shad.cpp
rm nvidia.o